spring.application.name=terminalAutobusesBackend

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/terminal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Caracas&connectionCollation=utf8mb4_unicode_ci&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=elis12

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=America/Caracas

# JSON serialization
spring.jackson.time-zone=America/Caracas

# JWT
jwt.secret=miapp-gestion-terminales-secret-key-2026-cambiar-en-produccion
